language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 5.6
        - php: 7.0
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0

after_script:
  - CODECLIMATE_REPO_TOKEN="217150bcc0c6c1447d2e0c629545772c26f4fd7dcc604e36eaa6d88ab36e215c" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token: 217150bcc0c6c1447d2e0c629545772c26f4fd7dcc604e36eaa6d88ab36e215c

after_success:
    - php vendor/bin/coveralls -v
